### PR TITLE
Update examples to elm-webgl 3.0.0

### PR DESCRIPTION
**Pull request by aforemny**

### CODE REVIEW

**Comment by aforemny** [comment]
I'm guessing this is a duplicate of #288.

@Apanatshka: Is this right, or is there something that I'm missing? How come your commit mentions different paths than mine?

I don't mind merging #288 and marking this as invalid.

**Comment by Apanatshka** [comment]
I'm working off the 0.15 branch, which houses the new overhauled website. This may still be interesting to merge depending on how long it takes for the new website to be finished.

**Comment by evancz** [comment]
I think both changes are valuable. I want to get the new website done this week, but having the webgl examples back in the meantime would be good. @aforemny, can you take a look at the Examples.elm page to show the WebGL examples again?

**Comment by aforemny** [comment]
@evancz, I managed to build the website and test the examples. After adding the ```elm-webgl``` dependency again to ```elm-package.json``` they work fine. This can be merged now, if it still makes sense to do so.

**Comment by evancz** [comment]
Awesome, thank you!

**Pull request merged**
