### PR TITLE
Pin "latest" to appropriate versions in announcement posts

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Some of these posts already had a mixture of `core/latest` and `core/concrete-version` links etc.

Now they all point to the versions that were "latest" at the time the respective Elm versions came out.

### CODE REVIEW

**Comment by evancz** [comment]
I believe I was trying to get these links to point to the libraries described in the posts. So in some cases you *want* the old link, and rely on the message on the package site if folks want the newer one.

There are too many here to easily figure out which ones are which.

**Comment by jvoigtlaender** [comment]
I don't understand. You say that in some cases one wants the old link and rely on the message on the package site if folks want the newer link. I think one *always* wants this. And that is exactly what this pull request achieves. So how is it not the right solution?

**Comment by evancz** [comment]
People are reading an old post. If they jump to docs that are inconsistent with that post, it would be weird.

**Comment by jvoigtlaender** [comment]
But that weird thing is going to happen *with how those pages are now*! My pull request stops that weird thing happening! That's what it's all about.

**Comment by evancz** [comment]
Ah, gotcha. For some reason I read the diff in the reverse order! Sorry for the confusion.

**Comment by evancz** [comment]
The title and description made it sound like the reverse was happening, at least how I read them.

**Comment by jvoigtlaender** [comment]
> Now they all point to the versions that were "latest" at the time the respective Elm versions came out.

:smile:

**Comment by jvoigtlaender** [comment]
Hah, by "now" I meant, "with my pull request". My bad, probably.

**Pull request merged**
