### PR TITLE
Favicon changed to logo + SVG version of logo

### PR DESCRIPTION
**Pull request by Apanatshka**
This should fix issue #208. 
I've reconstructed the tangram logo with the varying spacing. I think it's a better looking logo if the pieces can actually fit together, as opposed to the images I showed in the issue. 
The favicon [ICO file](https://en.wikipedia.org/wiki/ICO_%28file_format%29) contains image sizes 16, 32, 48, 64, 128, 256. Perhaps the HTML should include the HTML5 `<link rel="shortcut icon" size="16x16, 32x32, 48x48, 64x64, 128x128, 256x256" href="http://elm-lang.org/favicon.ico" />` as mentioned on [wikipedia](https://en.wikipedia.org/wiki/Favicon) and in this [thorough tutorial (that also shows how to do image tiles for mobile devices and Windows 8)](https://scotch.io/tutorials/all-favicons-for-all-devices-and-sizes).

### CODE REVIEW

**Comment by evancz** [comment]
Ah, thanks for referencing this! My designer friend created [an SVG version that keeps all the spaces even](https://github.com/elm-lang/package.elm-lang.org/blob/master/assets/elm_logo.svg). Can we use that spacing instead?

**Comment by evancz** [comment]
Also, sorry for the delay on this, I think I did not really understand that this was aiming to deal with the favicon.

Why not switch from the .png to the SVG in general? Are there cases where the .png is better?

**Comment by Apanatshka** [comment]
As I mentioned in #208, the even spaced version is no longer a tangram. When you remove the spacing, it doesn't form a square any more. I also like the old version better. But if you want the even spaced one, let me know and I'll change it. 

Switching completely to the SVG would have been a larger diff (because the PNG has a transparent border, and you'd have to add that in Elm for the SVG one). And I read somewhere that SVG is not supported on mobile browsers.

**Comment by evancz** [comment]
I think the even spacing is more important visually, so let's go with that. It is very hard to tell that the pieces don't line up exactly, but it's easy to see that the spaces are all different. Think of it as an artist's rendition, visually pleasing is more important than entirely true to life.

And I guess we should not change to SVG for that reason, though other sites have been showing SVG for a while, so that may be an issue over there if what you say is true.

**Comment by Apanatshka** [comment]
I just checked and on my phone I *can* view SVG images, so I guess what I read was wrong. Shall I change the logo to SVG and remove the PNG? (Maybe leave a "legacy-original-logo.png" file of the original you put up?)

**Comment by Apanatshka** [comment]
I left the PNG image there for now and switched to the SVG logo in the website code. I tried to replicate your code style. Let me know if you want anything else included in this PR.

**Comment by evancz** [comment]
Awesome, thank you!

I'm trying to figure out how to do a "PR monday" or something like that so that things are less likely to get lost, so hopefully we'll get something like that in place soon!

**Pull request merged**
