### PR TITLE
Better linking to ports explanation at various places

### PR DESCRIPTION
**Pull request by jvoigtlaender**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
In the ongoing endeavor of link fixing, how about merging this?

**Comment by evancz** [comment]
Can you get rid of the `#ports` on all the links? Then this should be good to go.

**Comment by jvoigtlaender** [comment]
Sure, will do if that's how you prefer it. (I don't obviously, but nevermind.)

**Comment by jvoigtlaender** [comment]
Did. So good to go.

**Comment by evancz** [comment]
Thanks!

**Pull request merged**
