### PR TITLE
Follow declaration rule in indentation example

### PR DESCRIPTION
**Pull request by danny-andrews**
Follow "Always bring the body of the declaration down one line" rule in indentation example.

### CODE REVIEW

**Comment by zwilias** [comment]
Yeah, that happens to be the one place where it's customary to bring down the assignment (`=`) as well, and where writing all of it on a single line is also acceptable.

[`elm-format`](https://github.com/avh4/elm-format) is pretty much the guideline for formatting code.

**Comment by danny-andrews** [comment]
Why the in consistency?

**Comment by zwilias** [comment]
Arguably, the current language just isn't very precise. In practice the rule is consistently enforced by elm-format for variable assignments (so functions and values), but not for type declarations, type alias declarations or type annotations.

A Github PR might not be the best place to discuss this further. If you want to talk about this more, I think one of the community forums like Slack, the elm-discuss mailing list or Reddit will provide a more productive environment for feedback.

**Comment by danny-andrews** [comment]
Thanks for the direction.

**Pull request closed without merging**
