### PR TITLE
adding link to NYC Meetup group

### PR DESCRIPTION
**Pull request by ethagnawl**

### CODE REVIEW

**Comment by evancz** [comment]
There are a lot of meetups now. I think it'd be good to keep a list somewhere, but I'd prefer if it was managed by the community. Makes sense to organize making this happen on elm-discuss or on slack.

**Comment by pootsbook** [comment]
I keep a list of meetups for [Elm Weekly](http://www.elmweekly.nl) as well as a scraper to expose events which I’ll be making public soon. For interested parties the current list of meetups (in no particular order) is as follows:

    Elm-user-group-SF
    Elm-User-Group-Dublin
    Elm-Warsaw
    Tokyo-Elm-Programming-Meetup
    Boston-Elm
    portlandelm
    Elm-Copenhagen
    ElmShop
    Boston-Elm-Lang-Meetup
    Elm-User-Group-DC
    Elm-London-Meetup
    STLElm
    Elm-NYC
    Stockholm-Elm
    Seattle-Elm
    Meetup-Elm-Paris
    chicago-elm
    Utah-Elm-Users
    Vienna-Elm-Meetup
    Elm-Berlin
    Elm-TLV
    Elmsinki
    berlin-elm-hackathon
    Elm-Wellington
    Elm-Zurich
    Sydney-Elm-Meetup
    Elmoin
    Elm-Portland-Maine
    oslo-elm-meetup
    Hangzhou-Elm-Meetup
    Brno-Elm-Meetup
    Elm-user-group-Vancouver

Details available at `"http://www.meetup.com/" ++ meetupId`

**Comment by evancz** [comment]
I haven't seen that before, that's awesome! :D If you end up with a page that links to all these, please share the link with me and I'll add it to this section.

**Comment by pootsbook** [comment]
@evancz Finally managed to get a list of meetup groups together in a linkable place: 

https://www.elmlog.com/meetup_groups 

Needs a bit of work, but it’s a start.

**Pull request closed without merging**
