### PR TITLE
Add cities with meetups to the website

### PR DESCRIPTION
**Pull request by bcardarella**
Not final, I'm sure the content should be different but I think it would be nice to list the cities with meetups on the website

### CODE REVIEW

**Comment by evancz** [comment]
There was a discussion on slack about this. Apparently @pootsbook has an automatically generated list of everything in the world. I'd rather link to that and have it maintain itself.

**Comment by pootsbook** [comment]
List here for reference: https://github.com/elm-lang/elm-lang.org/pull/522#issuecomment-218620704 
(`Elm-Meetup-Munich` is the only addition since then)

**Comment by pootsbook** [comment]
List of meetup groups now living here: https://www.elmlog.com/meetup_groups

**Comment by bcardarella** [comment]
\o/

awesome @pootsbook  😄

**Comment by evancz** [comment]
That's awesome @pootsbook! Will add a link on the website!

**Pull request closed without merging**
