### PR TITLE
Adding a Get Started page and link in the docs (issue #327)

### PR DESCRIPTION
**Pull request by soupi**
I have created this by mixing and matching the [old getting started page](https://github.com/elm-lang/elm-lang.org/blob/5b6e0b993784f44399d7db938dd014df625db363/frontend/public/Get-Started.elm) and [my blog post](http://www.gilmi.xyz/post/2015/07/04/starting-elm) as a response to the request on [issue 327](https://github.com/elm-lang/elm-lang.org/issues/327).

I hope this is ok as a first draft at least.

### CODE REVIEW

**Comment by evancz** [comment]
Can you remove the change to the docs page for now? That is the primary route people take when learning Elm, and I don't think I want them to get to "here's how to install things" quite that early. I want them to see more code so that they are not downloading stuff on trust. In other words, I'd rather not mess with the current flow until I understand how this will change things.

Currently the installers for both Mac and Windows both will send you to Get-Started.elm which is rerouted [here](https://github.com/elm-lang/elm-lang.org/blob/master/src/backend/Router.hs#L174). I think we'd primarily want to change that redirect for now. We can do the change to the newb flow separately.

I have not read this doc yet, but my understanding is that it is a post-install doc, so it is written for people who have already installed things. Is that correct?

**Comment by soupi** [comment]
I'll remove the changes to the docs page.

[Here is a link to a readable version of the doc](https://gist.github.com/soupi/6df9d17d84a280a01cf3). You can probably skim it in like 10 seconds to understand the gist of it.

This doc tries to guide users through the first steps of using Elm tools and learning Elm. Part of it is a post-install doc, explaining the different tools one gets with elm-platform, and part of it is enumerating different resources to learn Elm, such as the elm guide, elm architecture, some blog posts and more, and offers a "path to Elm" by recommending an ordering for these resources. It also suggests a few basic "projects" to start writing Elm code.

Of course, it recommends using the Online Editor straight away before installing elm-platform.

**Comment by jvoigtlaender** [comment]
I've suggested some changes in https://github.com/soupi/elm-lang.org/pull/2 that change the perspective of this page toward "You are arriving here because you have installed Elm and at the end of that process were pointed toward http://elm-lang.org/Get-Started.elm".

Also worth considering, I think, is splitting the page. To serve the purpose of post-install information on which tools are available and how to use them, the page could end before the "Learning Elm" section. That section could be made a separate thing. In particular, currently the link http://elm-lang.org/Learn.elm simply redirects to http://elm-lang.org/docs. Maybe a more useful thing would be possible there. But that's then about the "newb flow" that Evan mentions and proposes to consider independently. So maybe could be a separate pull request and discussion.

But everything before the "Learning Elm" section in the current pull request is about "what do I have and do after having installed the Elm Platform". Which is exactly what is currently missing from the whole http://elm-lang.org site, and has been requested repeatedly on the mailing list and in GitHub issues. So it would be nice to not have to stall that because of the undecided other part.

**Comment by soupi** [comment]
Yes, maybe splitting the page is the right thing to do.

**Comment by jvoigtlaender** [comment]
@soupi, thanks for incorporating my suggestions.

@evancz, what do you think now about adding the documentation here up to [this line](https://github.com/elm-lang/elm-lang.org/pull/370/files#diff-015471f8a6a2652b9ce3365cfb826b4fR151)? The section after that line could for the moment be replaced by a pointer to http://elm-lang.org/Learn.elm, and we could have separate discussion of guiding the learning workflow for newbies, based on the section here and what is already on the site.

**Comment by evancz** [comment]
This looks really great @soupi! Great work getting this all together :)

@jvoigtlaender, both of your suggestions make sense to me.

Is it okay to move this to `/get-started` like it was before? I kind of like it without the `docs/` in there because it reads like "elm lang, get started" more. Reasonable?

**Comment by soupi** [comment]
Yup, sounds reasonable.

**Pull request merged**
