### PR TITLE
Grammar changes

### PR DESCRIPTION
**Pull request by CWelshE**
Fixing missing commas, minor sentence structure errors, and whatever else I could find.

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
You do break code in there, in these lines:
```elm
      TimePlot occurances ->
          viewTimePlot occurrences
```

**Comment by CWelshE** [comment]
Oh, I knew there was another place where "occurrences" was listed. Thanks!

**Comment by jvoigtlaender** [comment]
@CWelshE, maybe split this into smaller chunks? See https://github.com/elm-lang/elm-lang.org/pull/433#issuecomment-160338448.

**Comment by CWelshE** [comment]
@jvoigtlaender Sure thing - just specify some degree of granularity, and you'll get it!

**Comment by evancz** [comment]
Can we do the spelling mistakes all in one go? Those are easy.

You like commas more than me, and you sometimes choose phrasing that is equivalent in meaning but feels less colloquial/fun to me. I'd do those on a more individual basis. Like, "this sentence is confusing for this reason, and this change fixes it"

**Comment by evancz** [comment]
Also, I'm more into descriptivism than proscriptivism when it comes to grammar, so I will tends towards "how I talk" over "technically correct" when there is a borderline case. Ultimately the goal is comprehension though.

**Comment by jvoigtlaender** [comment]
@CWelshE, this pull request is long stale. I don't think there is anything to do but close it. Evan has explained above in which form and chunk size he would prefer to see such changes. So that would motivate several smaller pull requests. But this one here should be closed.

**Pull request closed without merging**
