### PR TITLE
Changed elm-brackets link to my repo

### PR DESCRIPTION
**Pull request by tommot348**
I have forked and fixed the elm-brackets extension, as it is no longer maintained and had issues with linux/mac. I also added some stuff like code hinting and formatting and plan on developing it further.

### CODE REVIEW

**Comment by evancz** [comment]
Can you get someone else to confirm what's going on?

**Comment by tommot348** [comment]
Well, there are open issues on the original repo, to which the author himself replied that he has discontinued the project.
Am 26.07.2016 20:55 schrieb Evan Czaplicki <notifications@github.com>:Can you get someone else to confirm what's going on?

**Comment by evancz** [comment]
Give me a link to that.

I don't know stuff about brackets. Is there a "package install" thing as well? Will people be installing his or yours? Basically, if I am directing people to a project, will it work?

I need more information.

**Comment by tommot348** [comment]
https://github.com/lepinay/elm-brackets/issues/1
Brackets has a built-in extension manager. If you look for "elm" there, both his extension and mine will appear.
At the moment my extension is being worked on, but the version in the extension manager is working.
But I understand that you don't want to lose user due to bad tools, so if you have doubts, I would understand if you featured no link at all.
Am 26.07.2016 21:22 schrieb Evan Czaplicki <notifications@github.com>:Give me a link to that.

I don't know stuff about brackets. Is there a "package install" thing as well? Will people be installing his or yours? Basically, if I am directing people to a project, will it work?

I need more information.

**Comment by evancz** [comment]
Great, thanks for the additional context!

I'd suggest adding install instructions to your README so people know how to get it more easily. I'd also check with the other person to see if you can get their version taken out of there or something. Or have it redirect to you. Unclear.

**Pull request merged**
