### PR TITLE
Add backticks where appropriate

### PR DESCRIPTION
**Pull request by jonathanp**

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
Certainly this can be merged, @evancz?

**Comment by jvoigtlaender** [comment]
This PR now has conflicts.

**Comment by jonathanp** [comment]
Thanks, rebased now

**Comment by evancz** [comment]
Thanks for the changes, and sorry I did not get you a swifter response. I don't think I want to switch these. I decided not to put them in backticks originally, though perhaps that was the wrong decision. I feel that code font is distracting sometimes. Anyway, I think I want to keep these as they are.

**Pull request closed without merging**
