### PR TITLE
Redirect /examples/Intermediate.elm to /examples

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Part of fixing https://github.com/elm-lang/elm-lang.org/issues/450.

### CODE REVIEW

**Comment by evancz** [comment]
Can we fix the links instead?

**Comment by jvoigtlaender** [comment]
We can. But is it a good idea? We know that for several of the links in #450 there are links from *elsewhere* on the internet that have been 404ing for a while now. Those won't be fixed by changing links in the elm-lang.org source code.

Maybe that is not the case for this specific example. But it is the case for other links.

So, do we need to first categorize the links in #450 into two groups? Those that should be fixed somewhere in code, vs. those that should be redirects?

**Comment by evancz** [comment]
I'm not an expert at these things. My preference is that all links that we
own should just be updated to the right thing. If there's other stuff
online that need redirects, we can consider that separately I think.

On Thursday, December 17, 2015, Janis Voigtländer <notifications@github.com>
wrote:

> We can. But is it a good idea? We know that for several of the links in
> #450 <https://github.com/elm-lang/elm-lang.org/issues/450> there are
> links from *elsewhere* on the internet that have been 404ing for a while
> now. Those won't be fixed by changing links in the elm-lang.org source
> code.
>
> Maybe that is not the case for this specific example. But it is the case
> for other links.
>
> So, do we need to first categorize the links in #450
> <https://github.com/elm-lang/elm-lang.org/issues/450> into two groups?
> Those that should be fixed somewhere in code, vs. those that should be
> redirects?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elm-lang/elm-lang.org/pull/454#issuecomment-165688337>
> .
>


-- 
Sent from Gmail Mobile

**Comment by jvoigtlaender** [comment]
Okay. I'll make two replacement PRs then that change links directly. But let's keep in mind (maybe by collecting) links that once existed and still exist on the internet, and how to deal with them. For example, Bernd's list in #450 suggests that all previously existing links of the form "/edit/examples/$1/$2.elm" are now dead. Might make sense to add a generic redirect for those, to "/examples/$2".

**Pull request closed without merging**
