### PR TITLE
Add the game Achtung die Kurve

### PR DESCRIPTION
**Pull request by gbark**
Add [Achtung die Kurve](https://github.com/gbark/achtung) under Examples > Games > Community

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
How about adding it to http://builtwithelm.co/ (also or instead)? That site is already linked from the http://elm-lang.org/ front page, and seems to be where Elm example applications are primarily added these days.

**Comment by gbark** [comment]
Thought it could be useful with a multi player game under the examples, as all the others are single player.

**Comment by jvoigtlaender** [comment]
Sure, it's Evan's call. I think adding it to http://builtwithelm.co/ is a good idea regardless of whether or not it gets added to the Elm site proper.

**Comment by gbark** [comment]
Absolutely. Thanks for letting me know about http://builtwithelm.co/

**Comment by evancz** [comment]
Yeah, want to manage this sort of stuff on http://builtwithelm.co/

I will select ones to put on the website periodically as a separate process.

**Pull request closed without merging**
